"""correct scheme

Revision ID: 8ee13fdf1c28
Revises: create_initial_001
Create Date: 2025-08-20 12:46:13.759169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee13fdf1c28'
down_revision: Union[str, Sequence[str], None] = 'create_initial_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_type'), table_name='category')
    op.create_index(op.f('ix_category_type'), 'category', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_type'), table_name='category')
    op.create_index(op.f('ix_category_type'), 'category', ['type'], unique=True)
    # ### end Alembic commands ###
