name: Deploy to Oracle VM

on:
  push:
    branches:
      - main   # deploy when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}       
          username: ${{ secrets.SERVER_USER }}    
          key: ${{ secrets.SERVER_SSH_KEY }}      
          script: |
            set -e
            sudo mkdir -p /opt/my_budget_app
            sudo chown -R $USER:$USER /opt/my_budget_app 
            
            sudo mkdir -p /opt/my_budget_data
            sudo chown -R 999:999 /opt/my_budget_data  
            
            if [ ! -d "/opt/my_budget_app/.git" ]; then
              sudo git clone https://github.com/${GITHUB_REPOSITORY}.git /opt/my_budget_app
            else
              cd /opt/my_budget_app
              sudo git fetch origin main
              sudo git reset --hard origin/main
            fi
            
            cd /opt/my_budget_app
            sudo docker compose build
            sudo docker compose up -d
